# Generated by Django 4.2.3 on 2024-09-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Tags',
        ),
    ]
